package me.sankalpchauhan.dscmait.fragments;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import com.google.android.material.bottomsheet.BottomSheetDialogFragment;

import java.util.Random;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import me.sankalpchauhan.dscmait.R;

public class ContactusBottomSheet extends BottomSheetDialogFragment implements View.OnClickListener {
    private static final String ALLOWED_CHARACTERS ="0123456789qwertyuiopasdfghjklzxcvbnm";
    String name;
    String ID;
    String email;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.bottom_sheet_contactus, container, false);
         name = getArguments().getString("Name");
         ID= getArguments().getString("ID");
         email = getArguments().getString("Email");


        Button contact = v.findViewById(R.id.ContactUs);

        contact.setOnClickListener(this);

        return v;
    }

    @Override
    public void onClick(View v) {
        Intent emailIntent = new Intent(Intent.ACTION_SENDTO, Uri.parse("mailto:" + "support@sankalpchauhan.me"));
        emailIntent.putExtra(Intent.EXTRA_SUBJECT, "[Account Update Request] "+email);
        emailIntent.putExtra(Intent.EXTRA_TEXT, "Requestee "+name+" "+ID +" with \n Req. Ref. No.:- " +getRandomString(10)+"\n -----------DO NOT MODIFY----------- \n \n Please do not modify autogenerated lines Write your query here:- \n");
//emailIntent.putExtra(Intent.EXTRA_HTML_TEXT, body); //If you are using HTML in your body text

        startActivity(Intent.createChooser(emailIntent, "Choose Email Provider"));

    }


        private static String getRandomString(final int sizeOfRandomString)
        {
            final Random random=new Random();
            final StringBuilder sb=new StringBuilder(sizeOfRandomString);
            for(int i=0;i<sizeOfRandomString;++i)
                sb.append(ALLOWED_CHARACTERS.charAt(random.nextInt(ALLOWED_CHARACTERS.length())));
            return sb.toString();
        }

}
